language: node_js
node_js:
  - "6"
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test_async:
  script:
   - npm install
   - npm test
   - npm build
addons:
    code_climate:
        repo_token: 41e040597a8cc2d4de71c7c794e9c270cabc8383a1d3f12f114b9b168d04bebd
after_success:
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=41e040597a8cc2d4de71c7c794e9c270cabc8383a1d3f12f114b9b168d04bebd
  - ls coverage/PhantomJS*
  - codeclimate-test-reporter < "./coverage/lcov/PhantomJS 2.1.1 (Linux 0.0.0)/lcovonly"
